### ISSUE TITLE
magim map dont showing nothing its just in blank

### ISSUE THREAD

**Issue by adriango18** [TeamTwilight/twilightforest#1545]
### Forge Version

Forge_1.18.2_40.1.0

### Twilight Forest Version

twilightforest-1.18.2-4.1.1056-universal

### Steps to Reproduce

just thake the magic map go to the thetwilight forest world and ricght click, when u have the map already is not showing nothing

![image](https://user-images.githubusercontent.com/47388342/177009788-a3fdcd84-f879-4eac-8ae4-a85ba9159506.png)
![image](https://user-images.githubusercontent.com/47388342/177009806-efae66a5-be20-469d-85aa-029b56afb4e4.png)

### What You Expected

when i right click on the map its showing where i am on the world to see the biomes and see the boss, etc

### What Happened Instead

when i right click just is blank, no tshowing the map where i am to discover etc...

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Fixed by 869bc7bd1f059376f37b2c6906fb27728045db1e

**Comment by adriango18** [comment]
isnt fixed im still having this issue with the  last update 
![image](https://user-images.githubusercontent.com/47388342/178434074-7142339d-f3c7-4b1f-b8d5-a03685f5b4d0.png)
![image](https://user-images.githubusercontent.com/47388342/178434365-05ddcc0b-ef8f-46f1-8d08-fbcb366476a3.png)

mod version; twilightforest-1.18.2-4.1.1172-universal
forge version; Forge_1.18.2_40.1.0

**Comment by adriango18** [comment]
now i have the particles in all and i have this bug:

https://streamable.com/l1a9th

can u guys re open that and fix this pls? @Tamaized

**Comment by Tamaized** [comment]
The fix is in the 1.19 branch, not 1.18

**Comment by adriango18** [comment]
im on 1.18, i cant move to 1.19

**Comment by adriango18** [comment]
> im on 1.18, i cant move to 1.19

why not fix on 1.18, a lot of ppl play on this version,

**Comment by Tamaized** [comment]
I don't have a 1.18 workspace setup and ready to go, nor do I have the time. If another dev on the team wants to take the time to do so then they can. Usually when we work on a newer version we drop support for older versions.

**Comment by adriango18** [comment]
it makes no sense what you say, since you are still giving support for 1.18 since 1 day ago you updated the version of the mod for 1.18.

**Comment by Tamaized** [comment]
Another dev did that, I did not.
