### ISSUE TITLE
[1.18.2] java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Batimius** [TeamTwilight/twilightforest#1555]
### Forge Version

40.1.54

### Twilight Forest Version

4.1.1102

### Client Log

https://gist.github.com/Batimius/df9d82170716849111c1f0eab1ec31a4

### Crash Report (if applicable)

https://gist.github.com/Batimius/a69889f59f1c4bde6e2a9e36273bca12

### Steps to Reproduce

1. Launch Minecraft
2. Get this error

### What You Expected

I expected Minecraft to open up normally.

### What Happened Instead

It shows me the `Failure message: The Twilight Forest (twilightforest) encountered an error during the sided_setup event phase` error every time I launch it.

### Additional Details

I am using CurseForge alongside a lot of other mods. This error also seems to be happening sometimes, and sometimes it seems to work, at others it seems like it doesn't. Not sure what the issue is here.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Possibly fixed by e07c6bb7553dae8f6ceccb906bf96c6ec892053b
Hard to tell with the nature of this crash.

**Comment by Batimius** [comment]
> Possibly fixed by [e07c6bb](https://github.com/TeamTwilight/twilightforest/commit/e07c6bb7553dae8f6ceccb906bf96c6ec892053b) Hard to tell with the nature of this crash.

Definitely not fixed since I'm still getting this error even after using the latest version. Hopefully it'll be fixed soon.

**Comment by Tamaized** [comment]
That commit is in 1.19

**Comment by GizmoTheMoonPig** [comment]
pushed a fix for this for 1.18.2. The build currently isnt live on curseforge, but once it is feel free to give it a try
