### ISSUE TITLE
game exit

### ISSUE THREAD

**Issue by rjdxxxxxccc** [TeamTwilight/twilightforest#2020]
### NeoForge Version

47.2.21

### Twilight Forest Version

4.3.2145

### Client Log

https://gist.github.com/rjdxxxxxccc/708f05655d6aecdfecd44f5237e3fd0e

### Crash Report (if applicable)

https://gist.github.com/rjdxxxxxccc/886bf33fa78befe47a6609c2591fcb98

### Steps to Reproduce

When entering Naga's venue, the game will automatically save and exit.

### What You Expected

The game continues

### What Happened Instead

game exit

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Andromander** [comment]
This crash is caused by the mod Bad Optimizations. Removing it should fix the problem.

**Comment by jodlodi** [comment]
As it has been a while without a response, I will close that issue. If the above comment did not solve your problem, re-open this ticket with additional information
