### ISSUE TITLE
crash on sponge

### ISSUE THREAD

**Issue by zsn741656478** [TeamTwilight/twilightforest#410]
Forge version: 
Twilight Forest version: 3.6.300
Link to crash log: https://pastebin.com/GeH25GxQ

Steps to reproduce:
1. Player in the forest. I do not know how to crash.
2. When this player join the server again.The server crash immediately.

What I expected to happen:
Help me please.
My English no well, I'm sorry.

What happened instead:
The server crash.

**Comment by bs2609** [comment]
```
Caused by: java.lang.NullPointerException
	at twilightforest.structures.stronghold.ComponentTFStrongholdUpperLeftTurn.func_74875_a(ComponentTFStrongholdUpperLeftTurn.java:42) ~[ComponentTFStrongholdUpperLeftTurn.class:?]
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47) ~[bby.class:?]
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:603) ~[bbu.class:?]
	at twilightforest.world.ChunkGeneratorTwilightForest.func_185931_b(ChunkGeneratorTwilightForest.java:783) ~[ChunkGeneratorTwilightForest.class:?]
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:238) ~[SpongeChunkGeneratorForge.class:1.12.2-2555-7.1.0-BETA-2842]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1015) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:982) ~[axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) ~[on.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bak000(PlayerChunkMapEntry.java:1079) ~[ot.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) ~[ot.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147) ~[ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754) ~[MinecraftServer.class:?]
	... 4 more
```

Should be fixed by fa96c8928950bba48a0dedda30aadfa5c1f978db, I think.

**Comment by Tamaized** [comment]
Yes ^ has been fixed

**Comment by zsn741656478** [comment]
Sorry.I discover my crash log is the wrong.It is January 22 log. ><

This error on #315 versions has been fixed?
whether i need to reset the map(

**Comment by zsn741656478** [comment]
I updated to #315 versions. But my server still crash. What should I do?
crash log: https://pastebin.com/qPYdssA0

**Comment by 3TUSK** [comment]
@zsn741656478 请尝试最新的构建：http://builds.steamnsteel.info/browse/TF-ONETWELVE-316

**Comment by zsn741656478** [comment]
Thanks~
谢谢，你是开发者之一吗 @3TUSK

**Comment by 3TUSK** [comment]
@zsn741656478 不，我正好路过的，但还是欢迎前往 Twilight Forest 的 Discord 服务器：https://discord.gg/6v3z26B

**Comment by liach** [comment]
对，discord上面有很多打酱油的人可以帮你
